name: Publish Conda Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  conda-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          # Essential to prevent permission issues
          activate-environment: build_env
          auto-activate-base: false

      - name: Install build tools
        shell: bash -l {0}
        run: |
          conda install -y conda-build anaconda-client conda-verify

      - name: Build and Upload
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --set channel_priority strict

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "‚úÖ Version detected from Git Tag: $VERSION"
          else
            VERSION=$(grep -m1 'version = ' pyproject.toml | cut -d '"' -f2)
            echo "‚ö†Ô∏è No tag found. Fallback to pyproject.toml version: $VERSION"
          fi

          export PKG_VERSION=$VERSION
          echo "üöÄ Building Conda package version: $VERSION"
          sed -i "s/^  version: .*/  version: $VERSION/" recipe/meta.yaml || sed -i "s/^  version: .*/  version: $VERSION/" meta.yaml

          conda build . --output-folder dist -c conda-forge

          anaconda upload --label main dist/noarch/*.conda
